### ISSUE TITLE
RenderMediaOnLambda redeclared in this block

### ISSUE THREAD

**Issue by alexfernandez803** [remotion-dev/lambda_go_sdk#1]
The PR(https://github.com/remotion-dev/remotion/pull/2405/files) renames files.
packages/lambda-go/goclient.go → packages/lambda-go/lambda_go_sdk.go
packages/lambda-go/lambda_go_sdk_test.go

This project does not reflect the rename changes.

file goclient.go in this projec should be deleted as it is causing a 

> RenderMediaOnLambda redeclared in this block error

This happened during testing.

@JonnyBurger

**Comment by JonnyBurger** [comment]
Oh, good point! Thanks a lot, fixed in https://github.com/remotion-dev/remotion/commit/bfd1c4366af5457085d7e4eab808f70e15305508 now!
